name: Semgrep and Trivy Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  semgrep:
    name: Semgrep Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Semgrep Security Scan Started"
      - uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"

  trivy:
    name: Trivy Vulnerability Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner on local code
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
